# scene
scene: gibson
scene_id: Rs
#scene_id: 1pXnuDYAj8r
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_resolution: 0.1
trav_map_erosion: 2

hide_robot: false
num_robots: 2

# robot
robot: Turtlebot
is_discrete: False
velocity: 1.0

# task
task_random: true
target_dist_min: 1.0
target_dist_max: 5.0
goal_format: polar
task_obs_dim: 4
remove_finished_robots: true

# reward
reward_type: geodesic
success_reward: 10.0
potential_reward_weight: 1.0
collision_reward_weight: -0.1
#time_reward_weight: -1.0

# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.36  # body width
max_step: 500
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links

# sensor spec
output: [rgb, task_obs, adj_mat]

# graph
con_threshold: 1

# image
# ASUS Xtion PRO LIVE
# https://www.asus.com/us/3D-Sensor/Xtion_PRO_LIVE
fisheye: false
image_width: 224
image_height: 224
vertical_fov: 45
# depth
depth_low: 0.8
depth_high: 5
# scan
# Hokuyo URG-04LX-UG01
# https://www.hokuyo-aut.jp/search/single.php?serial=166
# n_horizontal_rays is originally 683, sub-sampled 1/3
n_horizontal_rays: 228
n_vertical_beams: 1
laser_linear_range: 5.6
laser_angular_range: 240.0
min_laser_dist: 0.05
laser_link_name: scan_link

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# visual objects
visual_object_at_initial_target_pos: false
target_visual_object_visible_to_agent: false

reset_orientation: true
reset_floor: true

reset_min_dist: 4
reset_max_dist: 8